- name: Playbook para reiniciar Hub
  hosts: all
  tasks:
    - name: check services
      win_service:
          name: Traditum.Hub.WinService
      register: result
      failed_when: result is not defined
      #ignore_errors: yes

    - debug: msg="{{result}}"

    - debug: msg="running"
      when: result.state is not defined or result.name is not defined
      
    - name: Check if the service exists
      raw: cmd /c sc query Traditum.Hub.WinService
      register: result2

    - debug: msg="{{result2}}"      
