- name: Playbook para Chequear Status Hub
  hosts: all
  tasks:
    - name: check services
      win_service:
          name: Traditum.Hub.WinService
      register: result
      failed_when: result is not defined
      #ignore_errors: yes

    - debug: msg="{{result.state}}"

     
